### ISSUE TITLE
Улучшение хеширования

### ISSUE THREAD

**Issue by saippuakauppias** [TextDatasetCleaner/deduplicator#11]
1. Понизить регистр букв строки
2. Удалить знаки препинания. Список всех знаков тут (можно точно также импортить для удаления):
```
import string

print(string.punctuation)
```
3. Разбить строку на слова по пробелу
4. Удалить пустые строки (если были 2 пробела подряд)
5. Отсортировать полученный список
6. Склеить список обратно в строку
7. Отправить результат на хеширование

**Comment by bddin** [comment]
Closed #12
