### ISSUE TITLE
Разработать пользовательский интерфейс (UI)

### ISSUE THREAD

**Issue by saippuakauppias** [TextDatasetCleaner/deduplicator#14]
Можно взять за основу фреймворк Twitter Bootstrap: https://getbootstrap.com/docs/5.0/getting-started/introduction/

Например, какой-нибудь готовый example:
https://getbootstrap.com/docs/5.0/examples/
https://getbootstrap.com/docs/5.0/examples/sign-in/
https://getbootstrap.com/docs/5.0/examples/cover/

Сделать просто посредине заголовок (Deduplicator), а под ним форму с полем ввода строки, а ниже кнопку для отправки.

**Comment by OlesyaSokolova** [comment]
Сделано
