### ISSUE TITLE
Добавить Redis как хранилище хешей

### ISSUE THREAD

**Issue by saippuakauppias** [TextDatasetCleaner/deduplicator#15]
Чтобы не хранить хеши в памяти - можно использовать Key-Value Storage, например, Redis: https://redis.io/

Нужно установить его в системе, добавить python пакет для работы с ним: https://pypi.org/project/redis/ (_не забыть добавить его в requirements.txt_) и можно сменить в `deduplicator.py` способ хранения хешей.

Для проверки существования хеша использовать команду EXISTS: https://redis.io/commands/exists - в питонячем пакете это метод `.exists(хеш)`.
Для добавления нового хеша в базу использовать команду SET: https://redis.io/commands/set - в питонячем пакете это метод `.set(ключ, значение)`, где ключем у нас будет сам хеш, а значением, например, `1`.

**Comment by bddin** [comment]
Closed #17
