### ISSUE TITLE
Доработки flask и redis

### ISSUE THREAD

**Issue by saippuakauppias** [TextDatasetCleaner/deduplicator#19]
1. При инициализации подключения к redis необходимо добавить очистку базы от предыдущего состояния хешей:
https://github.com/TextDatasetCleaner/deduplicator/blob/main/deduplicator.py#L7
Метод для очистки: `rds.flushdb()`

2. Исправить переменную для получения пользовательского ввода: https://github.com/TextDatasetCleaner/deduplicator/blob/main/app.py#L21
Было `u` => нужно `input`

3. Добавить отправку результата через JSON: https://github.com/TextDatasetCleaner/deduplicator/blob/main/app.py#L22
Добавить сверху импорт `from flask import jsonify`, в 22 строке заменить отправку результата на:
```
return jsoninfy({"data": showdedupl(text)})
```

**Comment by bddin** [comment]
Closed #20
