### ISSUE TITLE
Добавить линтеры для проверки качества кода

### ISSUE THREAD

**Issue by saippuakauppias** [TextDatasetCleaner/deduplicator#2]
flake8
mypy
и по желанию black

Настройки линтеров можно подсмотреть вот тут: https://github.com/TextDatasetCleaner/TextDatasetCleaner/blob/master/setup.cfg

Лучше сразу добавлять для запуска в Github Actions, подсмотреть можно тут: https://github.com/TextDatasetCleaner/TextDatasetCleaner/blob/master/.github/workflows/lint.yml

**Comment by bddin** [comment]
Closed #9

**Comment by bddin** [comment]
Closed #9
