### ISSUE TITLE
Выбрать хеш-функцию и добавить пример использования

### ISSUE THREAD

**Issue by saippuakauppias** [TextDatasetCleaner/deduplicator#3]
Скорее всего надо копать в сторону SimHash, но в issue #1 были и другие алгоритмы хеширования - можно вначале посмотреть подойдет ли какой-то из них.

Добавить python-скрипт, внутри которого будет функция, которая на вход принимает строку, а в результате выдает `True` - если данная строка является дублем какой-то другой строки, которая уже есть в базе (пока что всё будет храниться в памяти), и `False` - если строка не является дублем (в этом случае она внутри функции хеш строки должен добавляться в ту самую базу).

PS: проще всего это реализовать в виде класса, чтобы не было использования `global` для задания глобальных переменных в функции.

**Comment by bddin** [comment]
Closed #7
