### ISSUE TITLE
Добавить Flask

### ISSUE THREAD

**Issue by saippuakauppias** [TextDatasetCleaner/deduplicator#6]
Flask - это микро-фреймворк, он будет удобен для отправки на него строк и получения результата из базы хешей (является дубликатом из базы или нет).

В рамках этой задачи устанавливаем локально Flask, добавляем "Hello World" из примера и пробуем запустить встроенный dev-server, чтобы проверить работоспособность в браузере.

Flask docs: https://flask.palletsprojects.com/en/1.1.x/
Tutorial: https://flask.palletsprojects.com/en/1.1.x/quickstart/#a-minimal-application

**Comment by bddin** [comment]
Closed #7
